api:
  extends:
    file: _common.yml
    service: api
  links:
  - mongo
  - smtp
  ports:
  - 5000:5000

mongo:
  extends:
    file: _common.yml
    service: mongo

smtp:
  extends:
    file: _common.yml
    service: smtp

portal:
  extends:
    file: _common.yml
    service: portal
  ports:
  - 8090:8090

nodesdk:
  extends:
    file: _common.yml
    service: nodesdk
  links:
  - api
  environment:
  - pathwar_api_endpoint=http://api:5000/
  - pathwar_token=root-token
